In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

# 可視化モジュール
import matplotlib.pyplot as plt
import matplotlib as mpl
#import seaborn as sns
%matplotlib inline

# 小数第３まで表示
%precision 3

'%.3f'

In [3]:
Collision_data = pd.read_csv('NYC_accidents_heat_map.csv')
Collision_data.head()

C:\Users\yukihonzawa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,11/11/2017,0:00,BRONX,10468,40.866480,-73.895195,"(40.86648, -73.895195)",NaN,NaN,113 EAST KINGSBRIDGE ROAD,...,NaN,NaN,NaN,NaN,3787773,PASSENGER VEHICLE,BU,NaN,NaN,NaN
1,11/11/2017,0:00,BRONX,10475,40.868320,-73.833170,"(40.86832, -73.83317)",BARTOW AVENUE,EDSON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3788306,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
2,11/11/2017,0:00,BROOKLYN,11207,40.673150,-73.896194,"(40.67315, -73.896194)",PENNSYLVANIA AVENUE,GLENMORE AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3788809,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
3,11/11/2017,0:00,QUEENS,11428,40.718500,-73.735310,"(40.7185, -73.73531)",JAMAICA AVENUE,SPRINGFIELD BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,3787924,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
4,11/11/2017,0:00,QUEENS,11432,40.709785,-73.798180,"(40.709785, -73.79818)",NaN,NaN,87-32 165 STREET,...,Unspecified,NaN,NaN,NaN,3787575,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN

In [15]:
Collision_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139133 entries, 0 to 1139132
Data columns (total 29 columns):
DATE                             1139133 non-null object
TIME                             1139133 non-null object
BOROUGH                          821108 non-null object
ZIP CODE                         821029 non-null object
LATITUDE                         928495 non-null float64
LONGITUDE                        928495 non-null float64
LOCATION                         928495 non-null object
ON STREET NAME                   923773 non-null object
CROSS STREET NAME                875872 non-null object
OFF STREET NAME                  172400 non-null object
NUMBER OF PERSONS INJURED        1139133 non-null int64
NUMBER OF PERSONS KILLED         1139133 non-null int64
NUMBER OF PEDESTRIANS INJURED    1139133 non-null int64
NUMBER OF PEDESTRIANS KILLED     1139133 non-null int64
NUMBER OF CYCLIST INJURED        1139133 non-null int64
NUMBER OF CYCLIST KILLED         1139133 non-null int64
NUMBER OF MOTORIST INJURED       1139133 non-null int64
NUMBER OF MOTORIST KILLED        1139133 non-null int64
CONTRIBUTING FACTOR VEHICLE 1    1134198 non-null object
CONTRIBUTING FACTOR VEHICLE 2    988604 non-null object
CONTRIBUTING FACTOR VEHICLE 3    74260 non-null object
CONTRIBUTING FACTOR VEHICLE 4    15997 non-null object
CONTRIBUTING FACTOR VEHICLE 5    3927 non-null object
UNIQUE KEY                       1139133 non-null int64
VEHICLE TYPE CODE 1              1130641 non-null object
VEHICLE TYPE CODE 2              957242 non-null object
VEHICLE TYPE CODE 3              71920 non-null object
VEHICLE TYPE CODE 4              15393 non-null object
VEHICLE TYPE CODE 5              3803 non-null object
dtypes: float64(2), int64(9), object(18)
memory usage: 252.0+ MB

In [ ]:
# pd.to_datetime(Collision_data_frame['DATE']).month

In [5]:
Collision_data.DATE = pd.to_datetime(Collision_data.DATE)

In [17]:
per = Collision_data['DATE'].dt.to_period("M")
Collision_data.groupby(per)['NUMBER OF PERSONS KILLED'].sum()

DATE
2012-07    22
2012-08    27
2012-09    26
2012-10    21
2012-11    14
2012-12    27
2013-01    29
2013-02    20
2013-03    23
2013-04    16
2013-05    16
2013-06    23
2013-07    24
2013-08    35
2013-09    26
2013-10    23
2013-11    36
2013-12    26
2014-01    23
2014-02    13
2014-03    18
2014-04    22
2014-05    26
2014-06    22
2014-07    29
2014-08    22
2014-09    28
2014-10    20
2014-11    26
2014-12    13
           ..
2015-05    29
2015-06    20
2015-07    20
2015-08    22
2015-09    14
2015-10    24
2015-11    26
2015-12    22
2016-01    17
2016-02    19
2016-03    11
2016-04    12
2016-05    22
2016-06    26
2016-07    21
2016-08    29
2016-09    17
2016-10    21
2016-11    18
2016-12    24
2017-01    18
2017-02    13
2017-03    17
2017-04    23
2017-05    12
2017-06    21
2017-07    30
2017-08    21
2017-09    23
2017-10     9
Freq: M, Name: NUMBER OF PERSONS KILLED, Length: 64, dtype: int64

In [5]:
Dummy = pd.get_dummies(Collision_data['VEHICLE TYPE CODE 1'])

In [6]:
ZIP = Collision_data['ZIP CODE']
ZIP_frame = pd.DataFrame(ZIP)
a = pd.concat([ZIP_frame, Dummy], axis=1)

In [7]:
a = a.dropna()

In [7]:
a.groupby('ZIP CODE').sum()

,3D,AM,AMBUL,AMBULANCE,AR,Ambul,BA,BACKH,BICYCLE,BOBCA,...,sanit,schoo,subn,tank,tk,trail,truck,unk,unkno,van
ZIP CODE,,,,,,,,,,,,,,,,,,,,,
10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10001.0,0.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,54.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10002.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,73.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10003.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,66.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
10004.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10005.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10006.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10007.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10009.0,0.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,24.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10010.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,34.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10011.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,43.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10012.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,38.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10013.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,33.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10014.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,16.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10016.0,0.0,0.0,1.0,21.0,1.0,0.0,0.0,0.0,49.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10017.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,34.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10018.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,37.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10019.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,79.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10020.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10021.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,28.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10022.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,52.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10023.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,35.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10024.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,22.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10025.0,0.0,1.0,0.0,8.0,0.0,0.0,0.0,0.0,23.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10026.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,12.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10027.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,24.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10028.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,17.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10029.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,27.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10030.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10031.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,12.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11385,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11411,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11412,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11413,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11414,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11416,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11417,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11418,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11419,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11420,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11421,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11422,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11423,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11426,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11428,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11429,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11430,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11432,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11433,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11434,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11435,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11436,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11691,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11692,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11693,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11694,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11695,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11697,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
b = a
for i in range(len(a.columns)-1):
    if a.iloc[:, len(a.columns) - i -1].sum()<500 :
        b = b.drop(a.columns[len(a.columns) - i -1],axis=1)

In [9]:
b.head()

,ZIP CODE,AMBULANCE,BICYCLE,BUS,FIRE TRUCK,LARGE COM VEH(6 OR MORE TIRES),LIVERY VEHICLE,MOTORCYCLE,OTHER,PASSENGER VEHICLE,PICK-UP TRUCK,SMALL COM VEH(4 TIRES),SPORT UTILITY / STATION WAGON,TAXI,UNKNOWN,VAN
0,10468,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,10475,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,11207,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,11428,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,11432,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [72]:
b.groupby('ZIP CODE').sum()

,AMBULANCE,BICYCLE,BUS,FIRE TRUCK,LARGE COM VEH(6 OR MORE TIRES),LIVERY VEHICLE,MOTORCYCLE,OTHER,PASSENGER VEHICLE,PICK-UP TRUCK,SMALL COM VEH(4 TIRES),SPORT UTILITY / STATION WAGON,TAXI,UNKNOWN,VAN
ZIP CODE,,,,,,,,,,,,,,,
10000.0,0.0,17.0,0.0,0.0,1.0,0.0,1.0,1.0,47.0,1.0,0.0,24.0,25.0,0.0,4.0
10001.0,6.0,54.0,76.0,2.0,74.0,69.0,34.0,149.0,2420.0,118.0,121.0,884.0,1010.0,47.0,209.0
10002.0,10.0,72.0,43.0,4.0,27.0,37.0,38.0,85.0,2585.0,120.0,89.0,1008.0,352.0,42.0,109.0
10003.0,9.0,64.0,37.0,5.0,27.0,75.0,22.0,44.0,1513.0,78.0,99.0,497.0,544.0,34.0,94.0
10004.0,2.0,1.0,38.0,1.0,2.0,5.0,6.0,28.0,365.0,25.0,9.0,137.0,66.0,8.0,30.0
10005.0,2.0,6.0,3.0,0.0,2.0,7.0,5.0,29.0,215.0,16.0,8.0,62.0,35.0,10.0,22.0
10006.0,1.0,3.0,12.0,1.0,2.0,9.0,3.0,26.0,263.0,16.0,8.0,86.0,45.0,3.0,13.0
10007.0,1.0,21.0,32.0,0.0,6.0,14.0,7.0,43.0,739.0,24.0,18.0,247.0,152.0,15.0,50.0
10009.0,7.0,22.0,29.0,3.0,22.0,20.0,21.0,22.0,947.0,62.0,47.0,294.0,220.0,30.0,38.0
10010.0,10.0,34.0,44.0,1.0,23.0,63.0,18.0,53.0,1105.0,70.0,79.0,472.0,418.0,38.0,94.0
10011.0,13.0,42.0,34.0,3.0,40.0,66.0,41.0,98.0,1635.0,63.0,90.0,631.0,664.0,27.0,126.0
10012.0,2.0,38.0,10.0,3.0,25.0,49.0,29.0,46.0,1272.0,90.0,57.0,460.0,329.0,22.0,96.0
10013.0,3.0,32.0,54.0,3.0,58.0,66.0,30.0,132.0,2544.0,133.0,102.0,1013.0,383.0,45.0,142.0
10014.0,5.0,16.0,24.0,0.0,34.0,74.0,14.0,38.0,948.0,47.0,50.0,339.0,249.0,22.0,70.0
10016.0,21.0,46.0,94.0,1.0,67.0,67.0,22.0,97.0,2666.0,182.0,106.0,1132.0,797.0,63.0,219.0
10017.0,10.0,34.0,80.0,1.0,53.0,40.0,11.0,52.0,1650.0,89.0,63.0,620.0,602.0,36.0,130.0
10018.0,3.0,33.0,88.0,2.0,75.0,46.0,17.0,117.0,1908.0,117.0,136.0,684.0,619.0,36.0,165.0
10019.0,10.0,75.0,82.0,1.0,99.0,88.0,30.0,102.0,2833.0,140.0,117.0,964.0,852.0,33.0,193.0
10020.0,0.0,0.0,6.0,0.0,5.0,7.0,0.0,4.0,115.0,6.0,4.0,47.0,53.0,4.0,9.0
10021.0,2.0,27.0,22.0,2.0,36.0,44.0,16.0,66.0,928.0,37.0,26.0,354.0,270.0,27.0,70.0
10022.0,7.0,49.0,54.0,2.0,89.0,100.0,27.0,75.0,2614.0,151.0,94.0,1015.0,776.0,60.0,217.0
10023.0,1.0,32.0,34.0,1.0,28.0,67.0,25.0,32.0,1101.0,76.0,93.0,394.0,368.0,20.0,70.0
10024.0,6.0,23.0,30.0,2.0,26.0,42.0,15.0,32.0,1025.0,56.0,50.0,405.0,255.0,13.0,69.0
10025.0,9.0,21.0,25.0,2.0,46.0,57.0,23.0,49.0,1275.0,62.0,30.0,530.0,229.0,26.0,75.0
10026.0,2.0,11.0,9.0,0.0,6.0,3.0,16.0,19.0,721.0,27.0,12.0,245.0,97.0,21.0,33.0
10027.0,6.0,23.0,40.0,3.0,17.0,14.0,24.0,71.0,1646.0,63.0,28.0,562.0,172.0,62.0,73.0
10028.0,3.0,13.0,32.0,3.0,17.0,29.0,9.0,58.0,632.0,24.0,41.0,261.0,227.0,13.0,37.0
10029.0,21.0,29.0,48.0,11.0,26.0,35.0,23.0,91.0,1758.0,74.0,39.0,695.0,152.0,63.0,98.0
10030.0,5.0,6.0,7.0,1.0,5.0,14.0,8.0,23.0,749.0,25.0,15.0,293.0,85.0,23.0,27.0
10031.0,4.0,11.0,22.0,4.0,19.0,2.0,20.0,27.0,1037.0,36.0,20.0,246.0,76.0,23.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11385,4.0,4.0,51.0,5.0,78.0,8.0,29.0,135.0,2482.0,33.0,97.0,1177.0,26.0,94.0,135.0
11411,2.0,0.0,8.0,0.0,2.0,2.0,0.0,18.0,728.0,3.0,0.0,189.0,3.0,39.0,22.0
11412,2.0,2.0,20.0,2.0,11.0,2.0,1.0,23.0,1024.0,14.0,4.0,445.0,1.0,59.0,43.0
11413,4.0,1.0,27.0,0.0,17.0,1.0,8.0,54.0,1568.0,20.0,9.0,539.0,1.0,109.0,58.0
11414,1.0,1.0,9.0,1.0,5.0,3.0,4.0,17.0,621.0,19.0,3.0,261.0,3.0,46.0,23.0
11415,0.0,1.0,13.0,2.0,7.0,3.0,1.0,10.0,512.0,1.0,4.0,146.0,11.0,12.0,17.0
11416,5.0,0.0,9.0,4.0,10.0,2.0,1.0,22.0,832.0,7.0,13.0,239.0,17.0,25.0,15.0
11417,2.0,0.0,28.0,2.0,13.0,7.0,10.0,61.0,1088.0,19.0,4.0,441.0,10.0,74.0,44.0
11418,4.0,1.0,16.0,1.0,22.0,5.0,9.0,24.0,1179.0,19.0,19.0,324.0,30.0,22.0,30.0
11419,4.0,2.0,24.0,0.0,16.0,6.0,7.0,33.0,1406.0,19.0,6.0,543.0,27.0,64.0,41.0
11420,4.0,1.0,26.0,2.0,14.0,3.0,9.0,47.0,1341.0,28.0,7.0,550.0,16.0,100.0,68.0
11421,1.0,0.0,18.0,0.0,22.0,2.0,9.0,22.0,984.0,13.0,8.0,284.0,23.0,30.0,37.0
11422,2.0,1.0,18.0,1.0,11.0,1.0,3.0,34.0,1508.0,20.0,8.0,534.0,1.0,99.0,30.0
11423,1.0,0.0,34.0,0.0,14.0,5.0,2.0,22.0,847.0,15.0,15.0,359.0,7.0,41.0,40.0
11426,1.0,1.0,8.0,0.0,6.0,2.0,3.0,8.0,497.0,6.0,0.0,181.0,2.0,16.0,14.0
11427,0.0,0.0,11.0,0.0,6.0,1.0,3.0,16.0,698.0,8.0,6.0,227.0,2.0,37.0,23.0
11428,0.0,0.0,10.0,0.0,2.0,3.0,4.0,13.0,655.0,8.0,2.0,213.0,4.0,32.0,21.0
11429,0.0,2.0,13.0,0.0,3.0,0.0,2.0,23.0,793.0,3.0,4.0,210.0,0.0,34.0,24.0
11430,0.0,0.0,1.0,0.0,1.0,0.0,0.0,4.0,24.0,0.0,0.0,12.0,0.0,1.0,0.0
11432,12.0,1.0,121.0,6.0,16.0,21.0,6.0,30.0,1674.0,19.0,38.0,759.0,26.0,94.0,71.0
11433,5.0,0.0,63.0,1.0,18.0,9.0,4.0,47.0,1017.0,18.0,24.0,464.0,6.0,76.0,50.0
11434,2.0,2.0,60.0,2.0,36.0,10.0,13.0,109.0,2391.0,42.0,24.0,940.0,9.0,170.0,102.0
11435,3.0,0.0,62.0,7.0,28.0,18.0,11.0,37.0,1314.0,32.0,25.0,584.0,22.0,87.0,54.0
11436,1.0,1.0,11.0,1.0,3.0,4.0,1.0,11.0,452.0,23.0,4.0,217.0,3.0,25.0,18.0
11691,14.0,3.0,42.0,2.0,20.0,11.0,10.0,33.0,957.0,18.0,21.0,463.0,2.0,52.0,42.0
11692,4.0,0.0,7.0,1.0,3.0,1.0,3.0,5.0,263.0,11.0,6.0,109.0,1.0,12.0,14.0
11693,5.0,1.0,4.0,1.0,8.0,3.0,2.0,10.0,252.0,17.0,4.0,121.0,2.0,16.0,22.0
11694,2.0,1.0,6.0,0.0,15.0,4.0,3.0,16.0,282.0,12.0,14.0,135.0,1.0,17.0,14.0
11695,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,3.0,0.0,0.0,0.0
11697,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,20.0,3.0,0.0,17.0,0.0,3.0,5.0

In [81]:
Collision_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139133 entries, 0 to 1139132
Data columns (total 29 columns):
DATE                             1139133 non-null object
TIME                             1139133 non-null object
BOROUGH                          821108 non-null object
ZIP CODE                         821029 non-null object
LATITUDE                         928495 non-null float64
LONGITUDE                        928495 non-null float64
LOCATION                         928495 non-null object
ON STREET NAME                   923773 non-null object
CROSS STREET NAME                875872 non-null object
OFF STREET NAME                  172400 non-null object
NUMBER OF PERSONS INJURED        1139133 non-null int64
NUMBER OF PERSONS KILLED         1139133 non-null int64
NUMBER OF PEDESTRIANS INJURED    1139133 non-null int64
NUMBER OF PEDESTRIANS KILLED     1139133 non-null int64
NUMBER OF CYCLIST INJURED        1139133 non-null int64
NUMBER OF CYCLIST KILLED         1139133 non-null int64
NUMBER OF MOTORIST INJURED       1139133 non-null int64
NUMBER OF MOTORIST KILLED        1139133 non-null int64
CONTRIBUTING FACTOR VEHICLE 1    1134198 non-null object
CONTRIBUTING FACTOR VEHICLE 2    988604 non-null object
CONTRIBUTING FACTOR VEHICLE 3    74260 non-null object
CONTRIBUTING FACTOR VEHICLE 4    15997 non-null object
CONTRIBUTING FACTOR VEHICLE 5    3927 non-null object
UNIQUE KEY                       1139133 non-null int64
VEHICLE TYPE CODE 1              1130641 non-null object
VEHICLE TYPE CODE 2              957242 non-null object
VEHICLE TYPE CODE 3              71920 non-null object
VEHICLE TYPE CODE 4              15393 non-null object
VEHICLE TYPE CODE 5              3803 non-null object
dtypes: float64(2), int64(9), object(18)
memory usage: 252.0+ MB

In [10]:
data = Collision_data.loc[:,['LATITUDE','LONGITUDE','VEHICLE TYPE CODE 1']]

In [11]:
data.head()

    LATITUDE  LONGITUDE            VEHICLE TYPE CODE 1
0  40.866480 -73.895195              PASSENGER VEHICLE
1  40.868320 -73.833170  SPORT UTILITY / STATION WAGON
2  40.673150 -73.896194              PASSENGER VEHICLE
3  40.718500 -73.735310              PASSENGER VEHICLE
4  40.709785 -73.798180              PASSENGER VEHICLE

In [12]:
data['la'] = data['LATITUDE'].map(lambda x : round(float(x),3))
data['lo'] = data['LONGITUDE'].map(lambda x : round(float(x),3))

In [13]:
import math
la=[]
lo=[]
for i  in range(len(data)):
    if data['LATITUDE'][i]== np.nan:
         la.append(np.nan)
    else:
        la.append(round(float(data['LATITUDE'][i]),3))
    if math.isnan(float(data['LONGITUDE'][i])) == 'TRUE':
         lo.append(np.nan)
    else:
        lo.append(round(float(data['LONGITUDE'][i]),3))
location = pd.DataFrame({'la':la,'lo':lo})

In [14]:
data = data.dropna()

In [15]:
location = data.loc[:,['la','lo']]

In [16]:
location.head()

       la      lo
0  40.866 -73.895
1  40.868 -73.833
2  40.673 -73.896
3  40.718 -73.735
4  40.710 -73.798

In [17]:
Dummy = pd.get_dummies(data['VEHICLE TYPE CODE 1'])

In [18]:
a = pd.concat([location, Dummy], axis=1)

In [19]:
a.head()

,la,lo,3D,AM,AMBUL,AMBULANCE,AR,Ambul,BA,BACKH,...,sanit,schoo,subn,tank,tk,trail,truck,unk,unkno,van
0,40.866,-73.895,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,40.868,-73.833,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,40.673,-73.896,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,40.718,-73.735,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,40.710,-73.798,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
a = a.dropna()

In [21]:
b = a
for i in range(len(a.columns)-2):
    if a.iloc[:, len(a.columns) - i -1].sum()<500 :
        b = b.drop(a.columns[len(a.columns) - i -1],axis=1)

In [23]:
b.head()

,la,lo,AMBULANCE,BICYCLE,BUS,FIRE TRUCK,LARGE COM VEH(6 OR MORE TIRES),LIVERY VEHICLE,MOTORCYCLE,OTHER,PASSENGER VEHICLE,PICK-UP TRUCK,SMALL COM VEH(4 TIRES),SPORT UTILITY / STATION WAGON,TAXI,UNKNOWN,VAN
0,40.866,-73.895,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,40.868,-73.833,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,40.673,-73.896,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,40.718,-73.735,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,40.710,-73.798,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [22]:
c = b.groupby(['la','lo']).sum()

In [23]:
c.head()

                AMBULANCE  BICYCLE  BUS  FIRE TRUCK  \
la     lo
0.000   0.000         0.0      2.0  0.0         0.0
40.499 -74.244        0.0      0.0  0.0         0.0
       -74.243        0.0      0.0  0.0         0.0
       -74.242        0.0      0.0  0.0         0.0
40.500 -74.241        0.0      0.0  0.0         0.0

                LARGE COM VEH(6 OR MORE TIRES)  LIVERY VEHICLE  MOTORCYCLE  \
la     lo
0.000   0.000                              0.0             0.0         1.0
40.499 -74.244                             0.0             0.0         0.0
       -74.243                             0.0             0.0         0.0
       -74.242                             0.0             0.0         0.0
40.500 -74.241                             0.0             0.0         0.0

                OTHER  PASSENGER VEHICLE  PICK-UP TRUCK  \
la     lo
0.000   0.000     0.0               39.0            4.0
40.499 -74.244    0.0                2.0            0.0
       -74.243    0.0                0.0            0.0
       -74.242    0.0                0.0            0.0
40.500 -74.241    0.0                0.0            0.0

                SMALL COM VEH(4 TIRES)   SPORT UTILITY / STATION WAGON  TAXI  \
la     lo
0.000   0.000                       0.0                           24.0   3.0
40.499 -74.244                      0.0                            0.0   0.0
       -74.243                      0.0                            1.0   0.0
       -74.242                      0.0                            1.0   0.0
40.500 -74.241                      0.0                            1.0   0.0

                UNKNOWN  VAN
la     lo
0.000   0.000       0.0  0.0
40.499 -74.244      0.0  0.0
       -74.243      0.0  0.0
       -74.242      0.0  0.0
40.500 -74.241      0.0  0.0

In [24]:
c.iloc[:,1].sum()

4248.000

In [25]:
row_max = pd.DataFrame(np.max(c, axis=0),columns={'A'})
x = min(row_max['A'])
row_max

                                    A
AMBULANCE                        13.0
BICYCLE                           8.0
BUS                              71.0
FIRE TRUCK                        3.0
LARGE COM VEH(6 OR MORE TIRES)   29.0
LIVERY VEHICLE                   26.0
MOTORCYCLE                        8.0
OTHER                            49.0
PASSENGER VEHICLE               457.0
PICK-UP TRUCK                    32.0
SMALL COM VEH(4 TIRES)           28.0
SPORT UTILITY / STATION WAGON   192.0
TAXI                            153.0
UNKNOWN                          37.0
VAN                              47.0

In [31]:
df10 = c
i=0
j=0
for i in range(len(c.columns)):
    for j in range(len(c.index)):
       df10.iloc[j,i] = 1000*c.iloc[j,i]/sumi[i]
df10.head()

                AMBULANCE  BICYCLE  BUS  FIRE TRUCK  \
la     lo
0.000   0.000         0.0      0.0  0.0         0.0
40.499 -74.244        0.0      0.0  0.0         0.0
       -74.243        0.0      0.0  0.0         0.0
       -74.242        0.0      0.0  0.0         0.0
40.500 -74.241        0.0      0.0  0.0         0.0

                LARGE COM VEH(6 OR MORE TIRES)  LIVERY VEHICLE  MOTORCYCLE  \
la     lo
0.000   0.000                              0.0             0.0         0.0
40.499 -74.244                             0.0             0.0         0.0
       -74.243                             0.0             0.0         0.0
       -74.242                             0.0             0.0         0.0
40.500 -74.241                             0.0             0.0         0.0

                OTHER  PASSENGER VEHICLE  PICK-UP TRUCK  \
la     lo
0.000   0.000     0.0           0.000000            0.0
40.499 -74.244    0.0           0.003792            0.0
       -74.243    0.0           0.000000            0.0
       -74.242    0.0           0.000000            0.0
40.500 -74.241    0.0           0.000000            0.0

                SMALL COM VEH(4 TIRES)   SPORT UTILITY / STATION WAGON  TAXI  \
la     lo
0.000   0.000                       0.0                       0.000000   0.0
40.499 -74.244                      0.0                       0.000000   0.0
       -74.243                      0.0                       0.004362   0.0
       -74.242                      0.0                       0.004362   0.0
40.500 -74.241                      0.0                       0.004362   0.0

                UNKNOWN  VAN
la     lo
0.000   0.000       0.0  0.0
40.499 -74.244      0.0  0.0
       -74.243      0.0  0.0
       -74.242      0.0  0.0
40.500 -74.241      0.0  0.0

In [29]:
sumi = []
i=0
for i in range(len(c.columns)):
    sumi.append(c.iloc[:,i].sum())

In [30]:
sumi

[2094.000,
 4248.000,
 12340.000,
 725.000,
 11129.000,
 8304.000,
 5415.000,
 20715.000,
 527448.000,
 17106.000,
 12352.000,
 229237.000,
 39797.000,
 17864.000,
 23157.000]

In [32]:
df10max = []
i = 0
for i in range(len(df10.index)):
    df10max.append(df10.iloc[i,:].max())
df10_max = pd.DataFrame(df10max,index=df10.index,columns={'MAX'})

In [33]:
df = pd.concat([df10_max,df10], axis=1)
df.head()

                     MAX  AMBULANCE  BICYCLE  BUS  FIRE TRUCK  \
la     lo
0.000   0.000   0.000000        0.0      0.0  0.0         0.0
40.499 -74.244  0.003792        0.0      0.0  0.0         0.0
       -74.243  0.004362        0.0      0.0  0.0         0.0
       -74.242  0.004362        0.0      0.0  0.0         0.0
40.500 -74.241  0.004362        0.0      0.0  0.0         0.0

                LARGE COM VEH(6 OR MORE TIRES)  LIVERY VEHICLE  MOTORCYCLE  \
la     lo
0.000   0.000                              0.0             0.0         0.0
40.499 -74.244                             0.0             0.0         0.0
       -74.243                             0.0             0.0         0.0
       -74.242                             0.0             0.0         0.0
40.500 -74.241                             0.0             0.0         0.0

                OTHER  PASSENGER VEHICLE  PICK-UP TRUCK  \
la     lo
0.000   0.000     0.0           0.000000            0.0
40.499 -74.244    0.0           0.003792            0.0
       -74.243    0.0           0.000000            0.0
       -74.242    0.0           0.000000            0.0
40.500 -74.241    0.0           0.000000            0.0

                SMALL COM VEH(4 TIRES)   SPORT UTILITY / STATION WAGON  TAXI  \
la     lo
0.000   0.000                       0.0                       0.000000   0.0
40.499 -74.244                      0.0                       0.000000   0.0
       -74.243                      0.0                       0.004362   0.0
       -74.242                      0.0                       0.004362   0.0
40.500 -74.241                      0.0                       0.004362   0.0

                UNKNOWN  VAN
la     lo
0.000   0.000       0.0  0.0
40.499 -74.244      0.0  0.0
       -74.243      0.0  0.0
       -74.242      0.0  0.0
40.500 -74.241      0.0  0.0

1000.000

In [35]:
i = 0
row_max = []
x = 0
for i in range(len(df10.columns)):
    row_max.append(c.iloc[:,i].max())
x = min(row_max)
x

0.838

In [60]:
dfvan = df[df['VAN'] > 1]
dfvan.to_csv('dfvan.csv')

In [48]:
df[df.MAX > 1]

                     MAX  AMBULANCE   BICYCLE       BUS  FIRE TRUCK  \
la     lo
40.684 -73.935  4.137931   0.000000  0.235405  0.000000    4.137931
40.696 -73.985  4.137931   0.477555  0.470810  0.729335    4.137931
40.698 -73.869  4.137931   0.000000  0.000000  0.000000    4.137931
40.700 -73.944  4.775549   4.775549  0.235405  0.486224    0.000000
40.701 -73.942  3.820439   3.820439  0.000000  0.162075    1.379310
40.748 -74.004  4.775549   4.775549  0.235405  0.243112    0.000000
40.750 -73.995  3.115813   0.477555  0.000000  1.377634    0.000000
40.757 -73.990  5.753647   0.955110  0.470810  5.753647    0.000000
       -73.986  3.040430   0.955110  1.412429  2.188006    0.000000
40.758 -73.993  4.376013   0.477555  0.235405  4.376013    0.000000
40.759 -73.985  3.970827   0.955110  0.941620  3.970827    0.000000
40.760 -73.999  3.079417   0.000000  0.235405  3.079417    0.000000
40.764 -73.956  3.342884   3.342884  0.000000  0.567261    0.000000
40.813 -73.937  3.342884   3.342884  0.000000  0.000000    0.000000
40.818 -73.925  5.253104   5.253104  0.235405  0.162075    0.000000
40.857 -73.847  3.342884   3.342884  0.000000  0.081037    0.000000
40.881 -73.878  6.208214   6.208214  0.235405  0.972447    0.000000

                LARGE COM VEH(6 OR MORE TIRES)  LIVERY VEHICLE  MOTORCYCLE  \
la     lo
40.684 -73.935                        0.000000        0.000000    0.000000
40.696 -73.985                        2.246383        0.120424    0.369344
40.698 -73.869                        0.000000        0.000000    0.000000
40.700 -73.944                        0.089855        0.240848    0.000000
40.701 -73.942                        0.718843        0.120424    1.108033
40.748 -74.004                        0.269566        0.240848    0.554017
40.750 -73.995                        0.539132        0.722543    0.369344
40.757 -73.990                        1.168119        1.083815    0.184672
       -73.986                        0.539132        1.565511    0.369344
40.758 -73.993                        1.347830        0.842967    0.369344
40.759 -73.985                        2.515949        3.131021    0.184672
40.760 -73.999                        1.347830        0.240848    0.000000
40.764 -73.956                        0.628987        0.361272    0.184672
40.813 -73.937                        0.089855        0.120424    0.184672
40.818 -73.925                        0.089855        0.361272    0.369344
40.857 -73.847                        0.089855        0.000000    0.000000
40.881 -73.878                        0.089855        0.000000    0.000000

                   OTHER  PASSENGER VEHICLE  PICK-UP TRUCK  \
la     lo
40.684 -73.935  0.048274           0.026543       0.116918
40.696 -73.985  0.917210           0.866436       0.643049
40.698 -73.869  0.096548           0.058774       0.058459
40.700 -73.944  0.000000           0.091004       0.233836
40.701 -73.942  0.772387           0.219927       0.000000
40.748 -74.004  0.627565           0.208551       0.350754
40.750 -73.995  1.351678           0.373497       1.110721
40.757 -73.990  1.593049           0.502419       0.876885
       -73.986  1.303403           0.318515       1.227639
40.758 -73.993  1.303403           0.650301       0.876885
40.759 -73.985  0.579290           0.415207       0.701508
40.760 -73.999  2.365436           0.515691       0.701508
40.764 -73.956  0.241371           0.163049       0.233836
40.813 -73.937  0.048274           0.015167       0.058459
40.818 -73.925  0.096548           0.104276       0.233836
40.857 -73.847  0.048274           0.083421       0.058459
40.881 -73.878  0.144823           0.327994       0.058459

                SMALL COM VEH(4 TIRES)   SPORT UTILITY / STATION WAGON  \
la     lo
40.684 -73.935                 0.080959                       0.034898
40.696 -73.985                 1.781088                       0.793938
40.698 -73.869                 0.000000                       0.061072
40.700 -73.944                 0.242876                       0.095971
40.701 -73.942                 0.485751                       0.222477
40.748 -74.004                 0.404793                       0.248651
40.750 -73.995                 1.376295                       0.362071
40.757 -73.990                 0.971503                       0.340259
       -73.986                 1.052461                       0.274825
40.758 -73.993                 0.971503                       0.484215
40.759 -73.985                 1.619171                       0.405694
40.760 -73.999                 2.266839                       0.510389
40.764 -73.956                 0.404793                       0.174492
40.813 -73.937                 0.080959                       0.017449
40.818 -73.925                 0.080959                       0.157043
40.857 -73.847                 0.000000                       0.069797
40.881 -73.878                 0.080959                       0.191941

                    TAXI   UNKNOWN       VAN
la     lo
40.684 -73.935  0.025128  0.000000  0.043183
40.696 -73.985  0.753826  2.071205  0.561385
40.698 -73.869  0.000000  0.055979  0.000000
40.700 -73.944  0.075383  0.223914  0.000000
40.701 -73.942  0.175893  0.111957  0.431835
40.748 -74.004  1.382014  0.055979  0.604569
40.750 -73.995  3.115813  0.391850  1.079587
40.757 -73.990  3.844511  0.503807  1.425055
       -73.986  3.040430  0.279893  1.209138
40.758 -73.993  2.361987  0.895656  1.511422
40.759 -73.985  3.316833  0.279893  2.029624
40.760 -73.999  0.879463  0.391850  0.906853
40.764 -73.956  0.954846  0.055979  0.259101
40.813 -73.937  0.025128  0.000000  0.000000
40.818 -73.925  0.025128  0.223914  0.129550
40.857 -73.847  0.025128  0.000000  0.000000
40.881 -73.878  0.125638  0.391850  0.302284

In [49]:
i= 0
cmax = []
for i in range(len(df10.columns)):
    cmax.append(df.iloc[:,i].max())
cmax

[6.208,
 6.208,
 1.883,
 5.754,
 4.138,
 2.606,
 3.131,
 1.477,
 2.365,
 0.866,
 1.871,
 2.267,
 0.838,
 3.845,
 2.071]

In [72]:
print(np.where(max(df10.AMBULANCE)))

(array([0], dtype=int64),)

In [32]:
i = 0
df10_max = []
i = 0
for i in range(len(df10)):
    df10_max.append(df10.iloc[i,0].max())
df10max = pd.DataFrame(df10_max)

     0
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0

In [107]:
df1 = pd.DataFrame(d,columns={'MAX'},index=c.index)
df = pd.concat([df1, c], axis=1)
df.head()

                MAX  AMBULANCE  BICYCLE  BUS  FIRE TRUCK  \
la     lo
40.499 -74.244  2.0        0.0      0.0  0.0         0.0
       -74.243  1.0        0.0      0.0  0.0         0.0
       -74.242  1.0        0.0      0.0  0.0         0.0
40.500 -74.241  1.0        0.0      0.0  0.0         0.0
       -74.240  2.0        0.0      0.0  0.0         0.0

                LARGE COM VEH(6 OR MORE TIRES)  LIVERY VEHICLE  MOTORCYCLE  \
la     lo
40.499 -74.244                             0.0             0.0         0.0
       -74.243                             0.0             0.0         0.0
       -74.242                             0.0             0.0         0.0
40.500 -74.241                             0.0             0.0         0.0
       -74.240                             0.0             0.0         0.0

                OTHER  PASSENGER VEHICLE  PICK-UP TRUCK  \
la     lo
40.499 -74.244    0.0                2.0            0.0
       -74.243    0.0                0.0            0.0
       -74.242    0.0                0.0            0.0
40.500 -74.241    0.0                0.0            0.0
       -74.240    0.0                2.0            0.0

                SMALL COM VEH(4 TIRES)   SPORT UTILITY / STATION WAGON  TAXI  \
la     lo
40.499 -74.244                      0.0                            0.0   0.0
       -74.243                      0.0                            1.0   0.0
       -74.242                      0.0                            1.0   0.0
40.500 -74.241                      0.0                            1.0   0.0
       -74.240                      0.0                            0.0   0.0

                UNKNOWN  VAN
la     lo
40.499 -74.244      0.0  0.0
       -74.243      0.0  0.0
       -74.242      0.0  0.0
40.500 -74.241      0.0  0.0
       -74.240      0.0  0.0

In [62]:
np.mean(row_max)

2.757